application: cpe640-registrar-project 
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.application

- url: /scripts/update
  script: main.application

